import { FormEvent, useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { LoaderCircle, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { endpoints, errorMessage } from '../api'
import { PageHeader } from '../components/UI'

export default function Generate(){const [topic,setTopic]=useState('');const [workflow,setWorkflow]=useState('youtube_package');const [provider,setProvider]=useState('auto');const workflows=useQuery({queryKey:['workflows'],queryFn:endpoints.workflows});const providers=useQuery({queryKey:['providers'],queryFn:endpoints.providers});const navigate=useNavigate(),qc=useQueryClient();useEffect(()=>{const saved=localStorage.getItem('defaultWorkflow');if(saved)setWorkflow(saved)},[]);const mutation=useMutation({mutationFn:endpoints.generate,onSuccess:data=>{toast.success(`Job ${data.job_id.slice(0,8)} queued`);qc.invalidateQueries({queryKey:['jobs']});navigate('/jobs')},onError:e=>toast.error(errorMessage(e))});function submit(e:FormEvent){e.preventDefault();mutation.mutate({topic:topic.trim(),workflow,provider})}return <><PageHeader title="Generate" description="Launch a validated, scored and reflected content workflow."/><form onSubmit={submit} className="panel mx-auto max-w-3xl overflow-hidden"><div className="border-b border-slate-200 bg-gradient-to-r from-cyan-500/10 to-violet-500/10 p-6 dark:border-slate-800"><div className="mb-2 flex items-center gap-2 font-semibold"><Sparkles className="text-cyan-500"/>New content package</div><p className="text-sm text-slate-500">Choose a workflow and let the engine coordinate the rest.</p></div><div className="space-y-6 p-6"><label className="block"><span className="mb-2 block text-sm font-medium">Topic</span><textarea className="input min-h-32 resize-none" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="What should the content package explore?" required maxLength={500}/><span className="mt-1 block text-right text-xs text-slate-400">{topic.length}/500</span></label><div className="grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-medium">Workflow</span><select className="input" value={workflow} onChange={e=>setWorkflow(e.target.value)}>{workflows.data?.map(w=><option value={w.name} key={w.name}>{w.name.replaceAll('_',' ')}</option>)}</select></label><label><span className="mb-2 block text-sm font-medium">Provider</span><select className="input" value={provider} onChange={e=>setProvider(e.target.value)}><option value="auto">Auto failover</option>{providers.data?.filter(p=>p.configured).map(p=><option value={p.name} key={p.name}>{p.name}</option>)}</select></label></div>{workflows.data?.find(w=>w.name===workflow)&&<div className="rounded-xl border border-slate-200 p-4 text-sm dark:border-slate-700"><p className="font-medium">{workflows.data.find(w=>w.name===workflow)?.description}</p><p className="mt-2 text-slate-500">Plugins: {workflows.data.find(w=>w.name===workflow)?.plugins.join(', ')}</p></div>}<button className="btn-primary w-full" disabled={mutation.isPending||!topic.trim()}>{mutation.isPending?<LoaderCircle className="animate-spin" size={18}/>:<Sparkles size={18}/>}Generate package</button></div></form></>}
