import { FormEvent, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { KeyRound, Save, SlidersHorizontal } from 'lucide-react'
import { toast } from 'sonner'
import { endpoints } from '../api'
import { PageHeader } from '../components/UI'

type Form={openaiKey:string;geminiKey:string;tokenBudget:string;costBudget:string;defaultWorkflow:string}
export default function Settings(){const workflows=useQuery({queryKey:['workflows'],queryFn:endpoints.workflows});const [form,setForm]=useState<Form>(()=>({openaiKey:localStorage.openaiKey||'',geminiKey:localStorage.geminiKey||'',tokenBudget:localStorage.tokenBudget||'',costBudget:localStorage.costBudget||'',defaultWorkflow:localStorage.defaultWorkflow||'youtube_package'}));function save(e:FormEvent){e.preventDefault();Object.entries(form).forEach(([k,v])=>localStorage.setItem(k,v));toast.success('Dashboard settings saved locally')}function set<K extends keyof Form>(key:K,value:Form[K]){setForm({...form,[key]:value})}return <><PageHeader title="Settings" description="Configure dashboard defaults and private browser-local credentials."/><form onSubmit={save} className="space-y-6"><section className="panel p-6"><div className="mb-5 flex items-center gap-2"><KeyRound className="text-cyan-500"/><div><h2 className="font-semibold">API keys</h2><p className="text-xs text-slate-500">Stored only in this browser; server credentials remain environment-managed.</p></div></div><div className="grid gap-5 lg:grid-cols-2"><label><span className="mb-2 block text-sm font-medium">OpenAI API key</span><input className="input" type="password" value={form.openaiKey} onChange={e=>set('openaiKey',e.target.value)} placeholder="sk-••••••••"/></label><label><span className="mb-2 block text-sm font-medium">Gemini API key</span><input className="input" type="password" value={form.geminiKey} onChange={e=>set('geminiKey',e.target.value)} placeholder="••••••••"/></label></div></section><section className="panel p-6"><div className="mb-5 flex items-center gap-2"><SlidersHorizontal className="text-violet-500"/><h2 className="font-semibold">Generation defaults</h2></div><div className="grid gap-5 md:grid-cols-3"><label><span className="mb-2 block text-sm font-medium">Token budget</span><input className="input" type="number" min="1" value={form.tokenBudget} onChange={e=>set('tokenBudget',e.target.value)} placeholder="Unlimited"/></label><label><span className="mb-2 block text-sm font-medium">Cost budget (USD)</span><input className="input" type="number" step="0.01" min="0" value={form.costBudget} onChange={e=>set('costBudget',e.target.value)} placeholder="Unlimited"/></label><label><span className="mb-2 block text-sm font-medium">Default workflow</span><select className="input" value={form.defaultWorkflow} onChange={e=>set('defaultWorkflow',e.target.value)}>{workflows.data?.map(w=><option key={w.name} value={w.name}>{w.name.replaceAll('_',' ')}</option>)}</select></label></div></section><button className="btn-primary"><Save size={17}/>Save settings</button></form></>}
