import { FormEvent, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { KeyRound, Save, SlidersHorizontal } from 'lucide-react'
import { toast } from 'sonner'
import { endpoints } from '../api'
import { PageHeader } from '../components/UI'

type Form={apiKey:string;defaultWorkflow:string}
export default function Settings(){const workflows=useQuery({queryKey:['workflows'],queryFn:endpoints.workflows});const [form,setForm]=useState<Form>(()=>({apiKey:sessionStorage.getItem('techminddApiKey')||'',defaultWorkflow:localStorage.defaultWorkflow||'youtube_package'}));function save(e:FormEvent){e.preventDefault();sessionStorage.setItem('techminddApiKey',form.apiKey);localStorage.setItem('defaultWorkflow',form.defaultWorkflow);toast.success('Dashboard settings saved')}function set<K extends keyof Form>(key:K,value:Form[K]){setForm({...form,[key]:value})}return <><PageHeader title="Settings" description="Configure dashboard defaults and API access."/><form onSubmit={save} className="space-y-6"><section className="panel p-6"><div className="mb-5 flex items-center gap-2"><KeyRound className="text-cyan-500"/><div><h2 className="font-semibold">TechMindd API key</h2><p className="text-xs text-slate-500">Kept in session storage and sent only to the configured TechMindd API.</p></div></div><label><span className="mb-2 block text-sm font-medium">API key</span><input className="input" type="password" value={form.apiKey} onChange={e=>set('apiKey',e.target.value)} placeholder="Enter the server API key" autoComplete="off"/></label></section><section className="panel p-6"><div className="mb-5 flex items-center gap-2"><SlidersHorizontal className="text-violet-500"/><h2 className="font-semibold">Generation defaults</h2></div><label><span className="mb-2 block text-sm font-medium">Default workflow</span><select className="input" value={form.defaultWorkflow} onChange={e=>set('defaultWorkflow',e.target.value)}>{workflows.data?.map(w=><option key={w.name} value={w.name}>{w.name.replaceAll('_',' ')}</option>)}</select></label><p className="mt-3 text-xs text-slate-500">Provider token and cost budgets are enforced by the server deployment configuration.</p></section><button className="btn-primary"><Save size={17}/>Save settings</button></form></>}
